### ISSUE TITLE
'required' is set on all fields

### ISSUE THREAD

**Issue by arminio** [robfletcher/grails-angular-scaffolding#25]
Within the generated create.html and update.html files, the 'required' is set for all of the fields regardless whether they are nullable/blankable on the domain class.

I see that in the scafollding's renderFieldForProperty method  there is a 'required' boolean defined and it seems to do be doing the right thing. It's just not used when input field is being written out:

```
<input type="text" id="${prefix}${p.name}" name="${prefix}${p.name}"  required  data-ng-model="item.${prefix}${p.name}">
```

I fixed it for myself by:

```
<input type="text" id="${prefix}${p.name}" name="${prefix}${p.name}" <% if(required) print " required " %> data-ng-model="item.${prefix}${p.name}">
```

**Comment by robfletcher** [comment]
This should be fixed now with changes I've merged in from a branch.

**Comment by arminio** [comment]
I still get the same issue. I am not sure the fix has been applied to the actual plugin (angular-scaffolding:1.0-SNAPSHOT) yet. 

Code which has the "required" always set from templates\scaffolding\create.html:

```
private renderFieldForProperty(p, owningClass, prefix = "") {
        boolean hasHibernate = pluginManager?.hasGrailsPlugin('hibernate')
        boolean display = true
        boolean required = false
        if (hasHibernate) {
            cp = owningClass.constrainedProperties[p.name]
            display = (cp ? cp.display : true)
            required = (cp ? !(cp.propertyType in [boolean, Boolean]) && !cp.nullable && (cp.propertyType != String || !cp.blank) : false)
        }
        if (display) { %>
    <div class="control-group" data-ng-class="{error: errors.${prefix}${p.name}}">
        <label class="control-label" for="${prefix}${p.name}">${p.naturalName}</label>
        <div class="controls">
----------------->>>>>          <input type="text" id="${prefix}${p.name}" name="${prefix}${p.name}" required data-ng-model="item.${prefix}${p.name}">
            <span class="help-inline" data-ng-show="errors.${prefix}${p.name}">{{errors.${prefix}${p.name}}}</span>
        </div>
    </div>
```
